#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     MotorMotorServo, sensorI2CMuxController)
#pragma config(Sensor, S2,     Left_IR,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Right_IR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorB,          R_Spin,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          L_Spin,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     TowerLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    Gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//functions:
//encoder_forward(motor power, encoder counts);
//encoder_turn(turn45 or turn90", left or right,speed of motors);
//*/
#include "JoystickDriver.c"
#include "MyrobotLIB.h"
task main()
{

//right45enc();							//tested working
//right90enc();							//tested working
//left45enc();							//tested working
//left90enc();							//tested working
//encoder_forward(50,300);	//tested working
//encoder_backward(50,300);	//tested working
}
