#pragma config(Hubs,  S1, HTMotor,  HTMotor,  HTServo,  none)
#pragma config(Sensor, S1,     MotorMotorServo, sensorI2CMuxController)
#pragma config(Sensor, S2,     Left_IR,        sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S3,     Right_IR,       sensorHiTechnicIRSeeker1200)
#pragma config(Sensor, S4,     SMUX,           sensorI2CCustom)
#pragma config(Motor,  motorB,          R_Spin,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  motorC,          L_Spin,        tmotorNXT, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_1,     LeftMotor,     tmotorTetrix, PIDControl, encoder)
#pragma config(Motor,  mtr_S1_C1_2,     RightMotor,    tmotorTetrix, PIDControl, reversed, encoder)
#pragma config(Motor,  mtr_S1_C2_1,     TowerLift,     tmotorTetrix, openLoop)
#pragma config(Motor,  mtr_S1_C2_2,     Lift,          tmotorTetrix, openLoop, reversed)
#pragma config(Servo,  srvo_S1_C3_1,    Gripper,              tServoStandard)
#pragma config(Servo,  srvo_S1_C3_2,    servo2,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_3,    servo3,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_4,    servo4,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_5,    servo5,               tServoNone)
#pragma config(Servo,  srvo_S1_C3_6,    servo6,               tServoNone)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "JoystickDriver.c"  //Include file to "handle" the Bluetooth messages.

task main()
{
	while(true)
	{
//first joypad
		int threshold = 6; // Int 'threshold' will allow us to ignore low  readings that keep our robot in perpetual motion.
		if(abs(joystick.joy1_y1) > threshold)   // If the right analog stick's Y-axis readings are either above or below the threshold:
		{
		motor[motorE] = joystick.joy1_y1;         // Motor D is assigned a power level equal to the right analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
		motor[motorE] = 0;                        // Motor D is stopped with a power level of 0.
		}
		if(abs(joystick.joy1_y2) > threshold)   // If the left analog stick's Y-axis readings are either above or below the threshold:
		{
		motor[motorD] = joystick.joy1_y2;         // Motor E is assigned a power level equal to the left analog stick's Y-axis reading.
		}
		else                                    // Else if the readings are within the threshold:
		{
		motor[motorD] = 0;                        // Motor E is stopped with a power level of 0.
		}
//Second Joypad
		//Tower Lift--has two paralell motors mounted on the uprights
		if(joy2Btn(2))//A
			{
				motor[TowerLift]=80;//down
			}else if(joy2Btn(1))//B
				{
					motor[TowerLift]=-80;//up
				}else//not A, or B...
					{
					motor[TowerLift]=0;//stop
					}
	//lift--has one motor mounted at the tower cross-section
		if(joy2Btn(3))//X
			{
				motor[Lift]=-80;//down
			}else if(joy2Btn(4))//Y
				{
					motor[Lift]=80;//up
				}else//not X, or Y...
					{
					motor[Lift]=0;//stop
					}
	//Gripper
				if(joy2Btn(6))//LB
			{
			servo[Gripper]=100;
			}else//not LB...
				{
					servo[Gripper]=5;
				}
	}//while(true)
}//main end block
